/**
 * Centralized Company Configuration
 *
 * Update this file when deploying for a new company.
 * All branding, contact info, and company details are managed here.
 *
 * Auto-generated by setup-customer CLI tool
 * Generated: 2026-01-20T23:34:25.133Z
 */

export const companyConfig = {
  // Company Identity
  name: "West Peak Trenchless & Plumbing",

  // Website URL (for payment links, sharing, etc.)
  websiteUrl: "https://www.westpeakplumbing.com",
  legalName: "WEST PEAK TRENCHLESS & PLUMBING, LLC",
  shortName: "West Peak Plumbing",
  tagline: "Trenchless Solutions Done Right",
  description: "Professional trenchless and plumbing services serving the San Francisco Bay Area. Specializing in sewer repair, pipe lining, and full-service plumbing solutions.",

  // Contact Information
  phone: "(650) 379-8166",
  phoneRaw: "+16503798166",
  email: "servicerequests@westpeak.biz",

  // Business Details
  licenseNumber: "",
  address: {
    street: "1030 Duane Ave",
    city: "Santa Clara",
    state: "CA",
    zip: "95054",
    full: "1030 Duane Ave Santa Clara, CA 95054",
    region: "San Francisco Bay Area",
  },

  // Hours of Operation
  hours: {
    weekdays: "Mon - Fri: 7AM - 6PM",
    weekends: "Sat: 8AM - 4PM",
    emergency: "24/7 Emergency Service",
    schema: "Mo-Fr 08:00-17:00",
  },

  // Service Areas
  serviceAreas: [
      "Santa Clara",
      "San Jose",
      "Sunnyvale",
      "Mountain View",
      "Palo Alto",
      "Cupertino",
      "Los Altos",
      "Milpitas",
      "Fremont",
      "San Francisco"
  ],

  // Social Media Links
  social: {
    youtube: "",
    instagram: "",
    facebook: "",
    tiktok: "",
    google: "",
    yelp: "",
    linkedin: "",
  },

  // Logo
  logo: "/lovable-uploads/west-peak-logo.png",

  // SEO Defaults
  seo: {
    defaultTitle: "West Peak Plumbing - Trenchless Solutions Done Right",
    defaultDescription: "Professional trenchless and plumbing services serving the San Francisco Bay Area. Specializing in sewer repair, pipe lining, and full-service plumbing solutions.",
    defaultKeywords: "plumbing, contractor, San Francisco Bay Area",
    siteName: "West Peak Plumbing",
    author: "West Peak Plumbing",
  },

  // Ratings
  ratings: {
    average: "5.0",
    count: "0",
    best: "5",
    worst: "1",
  },

  // Pricing
  priceRange: "$$-$$$",

  // Services (customize based on construction type)
  services: [
    { name: "Service 1", path: "/services/1" },
    { name: "Service 2", path: "/services/2" },
  ],

  // Warranty Info
  warranty: {
    years: 25,
    description: "25-year warranty covering materials and workmanship",
  },

  // Geo coordinates (for schema.org)
  coordinates: {
    lat: 37.3585,
    lng: -121.9563,
  },
} as const;

// Type for the company config
export type CompanyConfig = typeof companyConfig;
