// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdjubzjqlegcybydbjvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkanViempxbGVnY3lieWRianZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NTE3MzEsImV4cCI6MjA4NDUyNzczMX0.fdvAGfYZ4wB3M8oFXZj0beX-2_cM0REHAwatJy5OcWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
